---
title: "r-project"
author: "Riley Maher, Griffin Rubin, Katie Summers, Natalie Vadasz"
date: "Dec 8, 2020"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Group Project

## Import Packages

```{r}
library("ggplot2")
library('dplyr')
library('tidyverse')
library('geosphere')
```

## Importing Data

```{r}
# Reading in the sample CSV of rider data we made
rider_2019_sample <- read.csv('sample.csv', stringsAsFactors = TRUE)
head(rider_2019_sample)

# Reading in the weather data set
weather_data <- read.csv('NYCWeather2019.csv', stringsAsFactors = TRUE)
head(weather_data)
```

## Initial Data Summary

```{r}
# Initial summary of rider data set
str(rider_2019_sample)
summary(rider_2019_sample)
```

```{r}
# Initial summart of weather data set
str(weather_data)
summary(rider_2019_sample)
```


## Initial Data Analysis

### Rider Age

```{r}
rider_2019_sample$age <- 2019 - as.numeric(as.character(rider_2019_sample$birth.year))
rider_2019_sample <- filter(rider_2019_sample, age <= 80)
```

### Gender Split in Riders

```{r}
# Reclassifying the genders
# 0=unknown, 1=male, 2=female
rider_2019_sample$gender <- ifelse(rider_2019_sample$gender == 0, "Unkown",
                                  ifelse(rider_2019_sample$gender == 1, "Male", "Female"))

# Seeing the split of genders who rented bikes
rider_2019_sample %>%
  ggplot(aes(x=gender)) +
  geom_bar()
```

### Subscriber vs Customer for Riders

```{r}
# Seeing the split of user type who rented bikes
rider_2019_sample %>%
  ggplot(aes(x=usertype)) +
  geom_bar()
```

### Trip Duration

```{r}
# Range of all bike rides
rider_2019_sample <- filter(rider_2019_sample, tripduration <= 3000)
duration_range <- range(rider_2019_sample$tripduration, na.rm=TRUE)
duration_range

# Average length of a bike ride
duration_mean <- mean(rider_2019_sample$tripduration, na.rm=TRUE)
duration_mean

# Standard deviation of bike rides
duration_sd <- sd(rider_2019_sample$tripduration, na.rm=TRUE)
duration_sd
```

### Types of Weather per Month

```{r}
# Creating columns of just month, day, and year
weather_data$DATE <- as.Date(weather_data$DATE, format = "%m/%d/%Y")
weather_data$Month <- format(weather_data$DATE, "%m")
weather_data$Day <- format(weather_data$DATE, "%d")
weather_data$Year <- format(weather_data$DATE, "%Y")
```


```{r}
# Average precipitation per month
weather_data %>% 
  summarise(average_precip = tapply(PRCP, Month, mean, na.rm=TRUE))
```

```{r}
# Average snow per month
weather_data %>% 
  summarise(avg_snow = tapply(SNOW, Month, mean, na.rm=TRUE))
```

```{r}
# Average wind speed per month
weather_data %>%
  summarise(average_wind_speed = tapply(AWND, Month, mean, na.rm=TRUE))
```

## Exploratory Data Analysis

### Distance Between Stations

```{r}
# Distance between start and end station in Meters

rider_2019_sample <- mutate(rider_2019_sample, 
                            distance = distHaversine(cbind(rider_2019_sample$start.station.longitude,
                                                           rider_2019_sample$start.station.latitude),
                                                     cbind(rider_2019_sample$end.station.longitude,
                                                           rider_2019_sample$end.station.latitude)))

head(rider_2019_sample)
```

```{r}
# Speed of the rider

rider_2019_sample$speed <- rider_2019_sample$distance/rider_2019_sample$tripduration

# Average speed of all riders
rider_2019_sample %>%
  summarise(average_speed = mean(speed))

# Average speed of young riders
rider_2019_sample %>%
  filter(age <= 45) %>%
  summarise(young_average = mean(speed))

# Average speed of old riders
rider_2019_sample %>%
  filter(age >= 65) %>%
  summarise(old_average = mean(speed))

# Average speed of female riders
rider_2019_sample %>%
  filter(gender == "Female") %>%
  summarise(female_average = mean(speed))

# Average speed of male riders
rider_2019_sample %>%
  filter(gender == "Male") %>%
  summarise(male_average = mean(speed))
```

```{r}
# Scatter Plot of speed by age

rider_2019_sample %>%
  ggplot(aes(x = speed, y = age)) +
  geom_point() +
  labs(title="Average Speed of Riders by Age", x="Speed", y="Age")
```

